# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
#   boot.initrd.postResumeCommands = lib.mkAfter ''
#     mkdir /btrfs_tmp
#     mount /dev/disk/by-label/nixos /btrfs_tmp
#     if [[ -e /btrfs_tmp/root ]]; then
#         mkdir -p /btrfs_tmp/old_roots
#         timestamp=$(date --date="@$(stat -c %Y /btrfs_tmp/root)" "+%Y-%m-%-d_%H:%M:%S")
#         mv /btrfs_tmp/root "/btrfs_tmp/old_roots/$timestamp"
#     fi
# 
#     delete_subvolume_recursively() {
#         IFS=$'\n'
#         for i in $(btrfs subvolume list -o "$1" | cut -f 9- -d ' '); do
#             delete_subvolume_recursively "/btrfs_tmp/$i"
#         done
#         btrfs subvolume delete "$1"
#     }
# 
#     for i in $(find /btrfs_tmp/old_roots/ -maxdepth 1 -mtime +30); do
#         delete_subvolume_recursively "$i"
#     done
# 
#     btrfs subvolume create /btrfs_tmp/root
#     umount /btrfs_tmp
#   '';
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b5679814-28d9-40e7-b3d0-3b8c551c92dc";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/b5679814-28d9-40e7-b3d0-3b8c551c92dc";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
